# Generated by Django 4.0.6 on 2022-10-12 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cadastro',
            new_name='Cadastros',
        ),
    ]
