# Generated by Django 4.0.6 on 2022-10-15 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_rename_cadastros_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='login',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
