# Generated by Django 4.0.6 on 2022-10-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_alter_cadastro_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastro',
            old_name='data_nasc',
            new_name='data_de_nascimento',
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='login',
            field=models.CharField(max_length=255),
        ),
    ]
